name: CI Pipeline

on :
   push:

jobs:
   build:
       runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Show build time
              run: echo "Build started at $(date)"

            - name: Run system info script
              run: bash devops/week1/case_study/scripts/system_info.sh

